version: '3'

services:
  docker_db:
    container_name: db_mysql
    image: mysql:5.7
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - my_volume:/var/lib/mysql

  src:
    depends_on:
      - docker_db
    env_file:
      - ./.env
    container_name: shift_api
    image: shift_api
    build:
      context: src
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    links:
      - docker_db

volumes:
  my_volume:
